name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    if: startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/release_matrix.yml
