name: Release

on:
  workflow_call: {}

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Get Workspaces
        id: workspaces
        # Get a list of all workspaces in the monorepo, and collect them into a
        # JSON array of objects with keys: name, path, and tagPattern
        run: |
          yarn workspaces list --json |
          jq --slurp 'map(select(.name | startswith("@")) | { name: .name, path: ("./" + .location), tagPattern: ("refs/tags/" + .location + "/v*") })'
          >> "$GITHUB_OUTPUT"

    outputs:
      workspaces: ${{ steps.workspaces.outputs.stdout }}

  release:
    runs-on: ubuntu-latest

    needs: info

    strategy:
      matrix:
        package: ${{ needs.info.outputs.workspaces }}

    steps:
      - if: startsWith(github.ref, matrix.package.tagPattern)
        uses: ./.github/workflows/release-matrix.yml
        with:
          workingDirectory: matrix.package.path