name: Release / NPM

on:
  workflow_call:
    inputs:
      name:
        description: 'The name of the package to release'
        required: true
        type: string
      workingDirectory:
        description: 'The directory of the package to release'
        required: true
        type: string
      tagPattern:
        description: 'The tag pattern to match'
        required: true
        type: string

jobs:
  release:
    name: ${{ inputs.name }}

    runs-on: ubuntu-latest

    if: startsWith(github.ref, inputs.tagPattern)

    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Check For Release
        shell: bash
        run: |
          if [[ ${{startsWith(github.ref, inputs.tagPattern)}} ]] ; then
            echo "This is a release tag"
          else
            echo "This is not a release tag"
            exit 1
          fi

      - name: Set up Node
        uses: ./.github/actions/setup-node

      - name: types
        run: yarn tsc:workspace

      - name: build
        run: yarn build

      - name: Publish package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}